### ISSUE TITLE
Can you also include the 64 bit version?

### ISSUE THREAD

**Issue by QuantumInformation** [adamhooper/selenium-server-standalone-jar#12]

**Comment by adamhooper** [comment]
I don't understand this request.

This library contains Java bytecode. Java bytecode is platform agnostic: it doesn't come in 32-bit or 64-bit versions.

@QuantumInformation Could you please clarify your request?

**Comment by QuantumInformation** [comment]
Yeah, it turned out it was a different error than what the window user reported.
